// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: diamond_wallet.proto

package diamond_wallet

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiamondWalletDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *DiamondWallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DiamondWalletDetail) Reset() {
	*x = DiamondWalletDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diamond_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiamondWalletDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiamondWalletDetail) ProtoMessage() {}

func (x *DiamondWalletDetail) ProtoReflect() protoreflect.Message {
	mi := &file_diamond_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiamondWalletDetail.ProtoReflect.Descriptor instead.
func (*DiamondWalletDetail) Descriptor() ([]byte, []int) {
	return file_diamond_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *DiamondWalletDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DiamondWalletDetail) GetData() *DiamondWallet {
	if x != nil {
		return x.Data
	}
	return nil
}

type DiamondWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber  string `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	BalanceDiamond uint64 `protobuf:"varint,4,opt,name=balance_diamond,json=balanceDiamond,proto3" json:"balance_diamond,omitempty"`
}

func (x *DiamondWallet) Reset() {
	*x = DiamondWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diamond_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiamondWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiamondWallet) ProtoMessage() {}

func (x *DiamondWallet) ProtoReflect() protoreflect.Message {
	mi := &file_diamond_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiamondWallet.ProtoReflect.Descriptor instead.
func (*DiamondWallet) Descriptor() ([]byte, []int) {
	return file_diamond_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *DiamondWallet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DiamondWallet) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DiamondWallet) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *DiamondWallet) GetBalanceDiamond() uint64 {
	if x != nil {
		return x.BalanceDiamond
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserID) Reset() {
	*x = UserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diamond_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_diamond_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_diamond_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *UserID) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateDiamondReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BalanceDiamond uint64 `protobuf:"varint,2,opt,name=balance_diamond,json=balanceDiamond,proto3" json:"balance_diamond,omitempty"`
}

func (x *UpdateDiamondReq) Reset() {
	*x = UpdateDiamondReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diamond_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDiamondReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiamondReq) ProtoMessage() {}

func (x *UpdateDiamondReq) ProtoReflect() protoreflect.Message {
	mi := &file_diamond_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiamondReq.ProtoReflect.Descriptor instead.
func (*UpdateDiamondReq) Descriptor() ([]byte, []int) {
	return file_diamond_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDiamondReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateDiamondReq) GetBalanceDiamond() uint64 {
	if x != nil {
		return x.BalanceDiamond
	}
	return 0
}

type StatusOK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatusOK) Reset() {
	*x = StatusOK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diamond_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusOK) ProtoMessage() {}

func (x *StatusOK) ProtoReflect() protoreflect.Message {
	mi := &file_diamond_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusOK.ProtoReflect.Descriptor instead.
func (*StatusOK) Descriptor() ([]byte, []int) {
	return file_diamond_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *StatusOK) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_diamond_wallet_proto protoreflect.FileDescriptor

var file_diamond_wallet_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x13, 0x44,
	0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x22,
	0x21, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x54, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6d,
	0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x27, 0x0a, 0x0f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x61, 0x6d, 0x6f,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x22, 0x24, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4f, 0x4b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xe3,
	0x01, 0x0a, 0x14, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x14, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x12,
	0x63, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4f, 0x4b,
	0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x3a, 0x01, 0x2a, 0x1a, 0x17, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2d, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64,
	0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_diamond_wallet_proto_rawDescOnce sync.Once
	file_diamond_wallet_proto_rawDescData = file_diamond_wallet_proto_rawDesc
)

func file_diamond_wallet_proto_rawDescGZIP() []byte {
	file_diamond_wallet_proto_rawDescOnce.Do(func() {
		file_diamond_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_diamond_wallet_proto_rawDescData)
	})
	return file_diamond_wallet_proto_rawDescData
}

var file_diamond_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_diamond_wallet_proto_goTypes = []interface{}{
	(*DiamondWalletDetail)(nil), // 0: proto.DiamondWalletDetail
	(*DiamondWallet)(nil),       // 1: proto.DiamondWallet
	(*UserID)(nil),              // 2: proto.UserID
	(*UpdateDiamondReq)(nil),    // 3: proto.UpdateDiamondReq
	(*StatusOK)(nil),            // 4: proto.StatusOK
}
var file_diamond_wallet_proto_depIdxs = []int32{
	1, // 0: proto.DiamondWalletDetail.data:type_name -> proto.DiamondWallet
	2, // 1: proto.DiamondWalletService.DetailWalletByUserID:input_type -> proto.UserID
	3, // 2: proto.DiamondWalletService.UpdateDiamondWallet:input_type -> proto.UpdateDiamondReq
	0, // 3: proto.DiamondWalletService.DetailWalletByUserID:output_type -> proto.DiamondWalletDetail
	4, // 4: proto.DiamondWalletService.UpdateDiamondWallet:output_type -> proto.StatusOK
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_diamond_wallet_proto_init() }
func file_diamond_wallet_proto_init() {
	if File_diamond_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_diamond_wallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiamondWalletDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diamond_wallet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiamondWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diamond_wallet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diamond_wallet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDiamondReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diamond_wallet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusOK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diamond_wallet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diamond_wallet_proto_goTypes,
		DependencyIndexes: file_diamond_wallet_proto_depIdxs,
		MessageInfos:      file_diamond_wallet_proto_msgTypes,
	}.Build()
	File_diamond_wallet_proto = out.File
	file_diamond_wallet_proto_rawDesc = nil
	file_diamond_wallet_proto_goTypes = nil
	file_diamond_wallet_proto_depIdxs = nil
}
